CREATE TABLE users (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_login varchar(50) NOT NULL,
	pass bytea NOT NULL,
	email varchar(120) NOT NULL,
	phone varchar(12),
	license varchar(100),
	about varchar,
	avatar varchar,
	birthday date,
	add_dt date NOT NULL,
	update_dt date NOT NULL
);